services:
  - type: web
    name: createdesk-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: createdesk-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VITE_BASE_URL
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
